# embed_web.cmake — Convert web assets to C byte arrays for compile-time embedding
#
# Usage in CMakeLists.txt:
#   set(WEB_DIR "${CMAKE_CURRENT_SOURCE_DIR}/web")
#   set(WEB_EMBED_CPP "${CMAKE_CURRENT_BINARY_DIR}/web_embed.cpp")
#   set(WEB_EMBED_H "${CMAKE_CURRENT_BINARY_DIR}/web_embed.h")
#   add_custom_command(
#     OUTPUT ${WEB_EMBED_CPP} ${WEB_EMBED_H}
#     COMMAND ${CMAKE_COMMAND}
#       -DWEB_DIR=${WEB_DIR}
#       -DOUTPUT_CPP=${WEB_EMBED_CPP}
#       -DOUTPUT_H=${WEB_EMBED_H}
#       -P ${CMAKE_CURRENT_SOURCE_DIR}/embed_web.cmake
#     DEPENDS ${WEB_DIR}/index.html ${WEB_DIR}/chat.js
#             ${WEB_DIR}/dashboard.js ${WEB_DIR}/style.css
#     COMMENT "Embedding web assets into C++ source"
#   )

# List of web files to embed: filename -> C identifier prefix
set(WEB_FILES
  "index.html:WEB_INDEX_HTML"
  "chat.js:WEB_CHAT_JS"
  "dashboard.js:WEB_DASHBOARD_JS"
  "files.js:WEB_FILES_JS"
  "system.js:WEB_SYSTEM_JS"
  "notifications.js:WEB_NOTIFICATIONS_JS"
  "install.js:WEB_INSTALL_JS"
  "style.css:WEB_STYLE_CSS"
  "login.html:WEB_LOGIN_HTML"
  "setup.html:WEB_SETUP_HTML"
)

# --- Generate header file ---
set(HEADER_CONTENT "#pragma once\n// Auto-generated by embed_web.cmake — do not edit\n\n")

foreach(entry ${WEB_FILES})
  string(REPLACE ":" ";" parts "${entry}")
  list(GET parts 1 varname)
  string(APPEND HEADER_CONTENT "extern const unsigned char ${varname}[];\n")
  string(APPEND HEADER_CONTENT "extern const unsigned int ${varname}_LEN;\n\n")
endforeach()

file(WRITE "${OUTPUT_H}" "${HEADER_CONTENT}")

# --- Generate source file ---
set(CPP_CONTENT "// Auto-generated by embed_web.cmake — do not edit\n")
string(APPEND CPP_CONTENT "#include \"web_embed.h\"\n\n")

foreach(entry ${WEB_FILES})
  string(REPLACE ":" ";" parts "${entry}")
  list(GET parts 0 filename)
  list(GET parts 1 varname)

  set(filepath "${WEB_DIR}/${filename}")

  if(NOT EXISTS "${filepath}")
    message(FATAL_ERROR "Web asset not found: ${filepath}")
  endif()

  # Read file as hex
  file(READ "${filepath}" file_content HEX)
  string(LENGTH "${file_content}" hex_len)
  math(EXPR byte_count "${hex_len} / 2")

  # Format as C hex array: 0xAB, 0xCD, ...
  set(hex_array "")
  set(col 0)
  string(REGEX MATCHALL ".." hex_bytes "${file_content}")

  foreach(byte ${hex_bytes})
    if(col EQUAL 0)
      string(APPEND hex_array "  ")
    endif()

    string(APPEND hex_array "0x${byte},")
    math(EXPR col "${col} + 1")

    if(col EQUAL 16)
      string(APPEND hex_array "\n")
      set(col 0)
    else()
      string(APPEND hex_array " ")
    endif()
  endforeach()

  # Append null terminator so it can also be used as a C string
  string(APPEND hex_array "0x00\n")
  math(EXPR byte_count "${byte_count} + 1")

  string(APPEND CPP_CONTENT "const unsigned char ${varname}[] = {\n${hex_array}};\n")
  # LEN does not include null terminator (reports actual file size)
  math(EXPR file_len "${byte_count} - 1")
  string(APPEND CPP_CONTENT "const unsigned int ${varname}_LEN = ${file_len};\n\n")
endforeach()

file(WRITE "${OUTPUT_CPP}" "${CPP_CONTENT}")

message(STATUS "Embedded web assets into ${OUTPUT_CPP} and ${OUTPUT_H}")
