// keygen.c — Ed25519 keypair generator for Llamaste update signing
//
// Generates:
//   signing-key.secret  — 64-byte Ed25519 secret key (NEVER commit this!)
//   signing-key.pub     — 32-byte Ed25519 public key
//   update_pubkey.h     — C header for embedding in the binary
//
// Build:
//   gcc -o keygen keygen.c ../src/llamaste/tweetnacl.c -I../src/llamaste
//
// Usage:
//   cd <project-root>
//   ./tools/keygen
//   cp update_pubkey.h src/llamaste/update_pubkey.h

#include "tweetnacl.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// TweetNaCl requires randombytes() to be provided externally.
#ifdef _WIN32
#include <windows.h>
#include <bcrypt.h>
#pragma comment(lib, "bcrypt.lib")
void randombytes(unsigned char *x, unsigned long long xlen) {
    BCryptGenRandom(NULL, x, (ULONG)xlen, BCRYPT_USE_SYSTEM_PREFERRED_RNG);
}
#else
#include <fcntl.h>
#include <unistd.h>
void randombytes(unsigned char *x, unsigned long long xlen) {
    int fd = open("/dev/urandom", O_RDONLY);
    if (fd < 0) { perror("open /dev/urandom"); exit(1); }
    while (xlen > 0) {
        ssize_t n = read(fd, x, (size_t)xlen);
        if (n <= 0) { perror("read /dev/urandom"); close(fd); exit(1); }
        x += n;
        xlen -= (unsigned long long)n;
    }
    close(fd);
}
#endif

static void write_hex(FILE *f, const unsigned char *data, int len) {
    for (int i = 0; i < len; i++) {
        fprintf(f, "0x%02x", data[i]);
        if (i < len - 1) fprintf(f, ", ");
        if ((i + 1) % 8 == 0 && i < len - 1) fprintf(f, "\n    ");
    }
}

int main(int argc, char *argv[]) {
    (void)argc; (void)argv;

    unsigned char pk[32], sk[64];

    if (crypto_sign_ed25519_keypair(pk, sk) != 0) {
        fprintf(stderr, "error: keypair generation failed\n");
        return 1;
    }

    // Write secret key
    FILE *f = fopen("signing-key.secret", "wb");
    if (!f) { perror("fopen signing-key.secret"); return 1; }
    if (fwrite(sk, 1, 64, f) != 64) { perror("fwrite"); fclose(f); return 1; }
    fclose(f);

    // Write public key (raw binary)
    f = fopen("signing-key.pub", "wb");
    if (!f) { perror("fopen signing-key.pub"); return 1; }
    if (fwrite(pk, 1, 32, f) != 32) { perror("fwrite"); fclose(f); return 1; }
    fclose(f);

    // Write C header
    f = fopen("update_pubkey.h", "w");
    if (!f) { perror("fopen update_pubkey.h"); return 1; }
    fprintf(f, "#pragma once\n");
    fprintf(f, "// update_pubkey.h -- Ed25519 public key for update signature verification\n");
    fprintf(f, "// Auto-generated by tools/keygen -- DO NOT EDIT\n");
    fprintf(f, "// The matching private key is in signing-key.secret (NEVER commit it!)\n\n");
    fprintf(f, "static const unsigned char UPDATE_PUBLIC_KEY[32] = {\n    ");
    write_hex(f, pk, 32);
    fprintf(f, "\n};\n");
    fclose(f);

    // Print summary
    printf("Ed25519 keypair generated successfully.\n\n");
    printf("  signing-key.secret  (64 bytes) -- KEEP PRIVATE, never commit!\n");
    printf("  signing-key.pub     (32 bytes) -- public key\n");
    printf("  update_pubkey.h     -- C header for embedding\n");
    printf("\nPublic key (hex): ");
    for (int i = 0; i < 32; i++) printf("%02x", pk[i]);
    printf("\n\nNext steps:\n");
    printf("  cp update_pubkey.h src/llamaste/update_pubkey.h\n");
    printf("  # Rebuild llamaste to embed the new key\n");

    // Scrub secret key from stack
    memset(sk, 0, sizeof(sk));

    return 0;
}
